name: budget_manager
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  dartz: ^0.10.1
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  path: ^1.9.0
  sqflite: ^2.4.0

dev_dependencies:
  build_runner: ^2.4.13
  mockito: ^5.4.4
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  test: ^1.25.7
  sqflite_common_ffi: ^2.3.4

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
