name: Flutter CI

on:
  pull_request:
    branches:
      - main

jobs:
  analyze:
    name: Dart Lint Analysis
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.4'

    - name: Install Dependencies
      run: flutter pub get

    - name: Analyze Code with Dart Linter
      run: flutter analyze

  test:
    name: Run Unit Tests and Coverage
    runs-on: ubuntu-latest
    needs: analyze

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.4'

    - name: Install Dependencies
      run: flutter pub get

    - name: Run Unit Tests
      run: flutter test --coverage

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: coverage/lcov.info

  build:
    name: Build APK
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.4'

    - name: Install Dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-release.apk
