name: Flutter CI

on:
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    outputs:
      flutter-cache: 
        description: 'Flutter setup complete'
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.4'

    - name: Install Dependencies
      run: flutter pub get

  analyze:
    name: Dart Lint Analysis
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.4'
        
    - name: Analyze Code with Dart Linter
      run: flutter analyze
      shell: bash

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.4'

    - name: Run Unit Tests
      run: flutter test --coverage
      shell: bash

  coverage:
    name: Coverage Report
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Generate Coverage Badge and Report
      run: bash <(curl -s https://codecov.io/bash) -f coverage/lcov.info
      shell: bash

    - name: Post Coverage Comment
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        message: "### Code Coverage Report $(cat coverage/lcov.info)"
